//app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import { Manrope, Comfortaa } from 'next/font/google'
import "./globals.css";
import Header from './components/Header'
import MainMenu from './components/MainMenu'
import Footer from './components/Footer'

const manrope = Manrope({
  subsets: ['latin', 'cyrillic'],
  weight: ['400','500','700'],
  variable: '--font-sans'
})

const comfortaa = Comfortaa({
  subsets: ['latin', 'cyrillic'],
  weight: ['500','700'],
  variable: '--font-heading'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${manrope.variable} ${comfortaa.variable} antialiased`}>
        <Header />
        <MainMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
